CREATE PROCEDURE [yedektendön]
AS
BEGIN
    
    ALTER DATABASE Etut SET OFFLINE WITH ROLLBACK IMMEDIATE; 

    RESTORE DATABASE Etut FROM DISK = 'C:\VTYedek\Etut.bak' WITH FILE = 1,
	NOUNLOAD, REPLACE;
	ALTER DATABASE Etut SET ONLINE;
    
   
END;